# Arming operation; might take time because of interfacing with the MCU.
#
# Roberto Masocco <r.masocco@dotxautomation.com>
#
# June 6, 2023

# GOAL
---
# RESULT
# Operation result
dua_interfaces/CommandResultStamped result
---
# FEEDBACK
