# Landing operation.
#
# Roberto Masocco <r.masocco@dotxautomation.com>
#
# June 6, 2023

# GOAL
# Decision position
geometry_msgs/PointStamped minimums
---
# RESULT
# Operation result
dua_interfaces/CommandResultStamped result
---
# FEEDBACK
# Current pose
geometry_msgs/PoseStamped pose
