# Navigation operation to a target pose.
#
# Roberto Masocco <r.masocco@dotxautomation.com>
#
# June 16, 2023

# GOAL
# Target pose
geometry_msgs/PoseStamped target
---
# RESULT
# Operation result
dua_interfaces/CommandResultStamped result
---
# FEEDBACK
# Current pose
geometry_msgs/PoseStamped current_pose
