# Takeoff operation.
#
# Roberto Masocco <r.masocco@dotxautomation.com>
#
# June 6, 2023

# GOAL
# Target position and orientation to reach upon takeoff
geometry_msgs/PoseStamped takeoff_pose
---
# RESULT
# Operation result
dua_interfaces/CommandResultStamped result
---
# FEEDBACK
# Current pose
geometry_msgs/PoseStamped current_pose
